"""LLMClient Protocol — vendor-agnostic interface."""
from __future__ import annotations

from typing import Protocol

from storytelling_bot.schema import Fact, Layer


class LLMClient(Protocol):
    def classify_fact(self, text: str) -> tuple[Layer, str, float]: ...
    def synthesize_layer(self, layer: Layer, facts: list[Fact]) -> str: ...
    def judge_red_flag(self, text: str) -> tuple[str, float] | None: ...
    def classify_green(self, text: str) -> bool: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
